#! /usr/bin/env python
# vim: set ai softtabstop=2 shiftwidth=2 tabstop=80 :


import signal
from tui_gui.select_menu import initialize, parse_args

def sigwinch_handler(signum, frame):
  if old_winch_handler:
    old_winch_handler(signum, frame)
  menu.show()

old_winch_handler = None
if __name__ == '__main__':
  old_winch_handler = signal.signal(signal.SIGWINCH, sigwinch_handler)
  initialize()
  menu = parse_args(('[sub1]','l1,text 1,t1|l2,text 2,t2','[sub2]','l22,text22,t22'))
  menu.show()
  print
  menu = parse_args('l1,text 1,t1|\\[\e[0;32m\\]l2\\[\e[0m\\],text 2,t2|l3,text 3,t3|l4,text 4,t4|l5,text 5,t5|l6,text 6,t6|l7,text 7,t7|l10,text 10,t10')
  item_choosen = menu.handle()
  if item_choosen == 'cancelled':
    print 'User cancelled the operation.'
  elif item_choosen != None:
    print(item_choosen.get_tag())
