#! /usr/bin/env python
# vim: set ai softtabstop=2 shiftwidth=2 tabstop=80 :


import signal
from optparse import OptionParser
from tui_gui.select_menu import Menu

def sigwinch_handler(signum, frame):
  if old_winch_handler:
    old_winch_handler(signum, frame)
  menu.show()
old_winch_handler = signal.signal(signal.SIGWINCH, sigwinch_handler)

parser = OptionParser(usage="%prog [options] RESULT_FILE MENU_ITEMS")
parser.add_option("-d", "--default_tag", 
                  help="Default tag to select. This will be selected when the user presses enter without entering anything.")
parser.add_option("-t", "--timeout", type="float", 
                  help="Timeout for the selection in seconds. If a default tag is indicated, this will be returned. When the timeout <= 0, it means no timeout.",
                  default=0)
parser.add_option("-p", "--prompt",
                  help="Prompt to show to the user",
                  default="Please make your choice: ")
(options, args) = parser.parse_args()
result_filename = args[0]
del args[0]
menu = Menu(args, prompt=options.prompt, default_tag=options.default_tag, timeout=options.timeout)
item_choosen = menu.handle()
result_file = file(result_filename, "w")
if item_choosen == Menu.CANCELLED:
  print >> result_file, ''
else:
  print >> result_file, item_choosen.get_tag()
result_file.close()
